### ISSUE TITLE
Improved Error Message When No API Exists on Path

### ISSUE THREAD

**Issue by MisterJames** [Azure/static-web-apps-cli#245] opened 2021-06-16 12:23 UTC
**Is your feature request related to a problem? Please describe.**
I've run into this a couple of times, and admittedly, it's a user problem ;)

In my scenario, I'm bringing my own client and using Azure Functions for the API, letting `swa` take care of the API startup. I provide the URI for the client and the path for the API, however, when I am in the wrong directory the API cannot be found. Computers are so picky. 

This is the error that you see:

```
C:\james\code> swa start http://localhost:8080/ --api .\Server\InfinityStone.Mapping\
[swa] - Waiting for http://0.0.0.0:7071 to be ready
[swa] ✖ Waiting for http://0.0.0.0:7071 to be ready
[swa] Could not connect to "http://0.0.0.0:7071". Is the server up and running?
[swa] node "C:\Users\james\AppData\Roaming\nvm\v14.17.0\node_modules\@azure\static-web-apps-cli\dist\msha\server.js" exited with code 0
```

If you notice I am in the `C:\james\code\` path but I should be in `C:\james\code\coolthings` path. It happens when I'm using, for example, Windows Terminal and I start up the client, then split off a pane to start the API, but I land in my default path.

**Describe the solution you'd like**
When a path is provided for the API rather than an http endpoint a quick check could be done to test if the path exists, which could give a more accurate error message. 

For example: `Could not find part or all of the path for  ".\Server\InfinityStone.Mapping\". Have you had your coffee this morning?`

_I would be happy to attempt a PR on this if you're open to the idea._

**Describe alternatives you've considered**
I have considered using the correct base path each time, but that feels like I would have to be more accurate and make less mistakes. I don't know if I can take that kind of pressure.

**Additional context**
I have a somewhat dry and stereotypical dad-like sense of humor and my jokes are often funnier to me than those around me.

**Comment by MisterJames** [comment] 2021-06-16 12:26
I did find this in the source, should this not take care of this problem?

https://github.com/Azure/static-web-apps-cli/blob/main/src/cli/commands/start.ts#L47

**Comment by manekinekko** [comment] 2021-06-16 12:45
Thank you @MisterJames for reporting this behavior. 

Yes, that piece of the code checks of the API folder exists, if not, we print a message (but we don't block – that's by design.

https://github.com/Azure/static-web-apps-cli/blob/ba94044c52614f8d6591a10ad8394301d733fd02/src/cli/commands/start.ts#L46-L48

Would you mind running your same command and adding `--verbose=silly` then printing the section where it says:

````
[swa] - ssl:
[swa]   - 0: false
[swa]   - 1: <undefined>
[swa]   - 2: <undefined>
[swa] - env:
[swa]   - SWA_CLI_DEBUG: silly
[swa]   - SWA_CLI_API_PORT: 7071
[swa]   - SWA_CLI_APP_LOCATION: /Users/wassimchegham/oss/@azure/static-web-apps-cli/
[swa]   - SWA_CLI_OUTPUT_LOCATION: /Users/wassimchegham/oss/@azure/static-web-apps-cli/
[swa]   - SWA_CLI_API_LOCATION: <undefined>
[swa]   - SWA_CLI_ROUTES_LOCATION: ./
[swa]   - SWA_CLI_HOST: 0.0.0.0
[swa]   - SWA_CLI_PORT: 4280
[swa]   - SWA_WORKFLOW_FILES: <undefined>
[swa]   - SWA_CLI_APP_SSL: false
[swa]   - SWA_CLI_APP_SSL_CERT: <undefined>
[swa]   - SWA_CLI_APP_SSL_KEY: <undefined>
[swa]   - SWA_CLI_STARTUP_COMMAND: <undefined>
[swa] - commands:
[swa]   - swa: node "/Users/wassimchegham/oss/@azure/static-web-apps-cli/dist/msha/server.js"
[swa]   - api: <undefined>
[swa]   - run: <undefined>
[swa] 
```

I am mainly interested in the valid of `SWA_CLI_API_LOCATION`.

**Comment by manekinekko** [comment] 2022-03-22 10:36
@MisterJames would you mind testing again with the [new version of the CLI](https://github.com/Azure/static-web-apps-cli/releases/tag/v0.8.3) and let us know if you are still having an issue. I am going to close this thread. Please feel free to reopen if needed.

**Closed by manekinekko** 2022-03-22 10:36 UTC
Labels: type: question
