### ISSUE TITLE
 Failed to load staticwebapp.config.json schema. Continuing without validation!

### ISSUE THREAD

**Issue by madilkha** [Azure/static-web-apps-cli#805] opened 2024-03-04 12:49 UTC
When using swa cli for the deployment to azure static web app with bitbecket pipeline, I got this error:

Deploying to environment: production
✖ Failed to load [staticwebapp.config.json](https://bitbucket.org/tkxel/signal-frontend/src/b9d282d1dd7801739b0496deca9f0d5e752b1c2e/staticwebapp.config.json) schema. Continuing without validation!

**Comment by itpropro** [comment] 2024-03-04 15:16
Probably a duplicate of #802

**Comment by cjk7989** [comment] 2024-03-07 07:40
Thanks for report! swa-cli@1.1.7 has been released and fixed this issue. So close it.

**Closed by cjk7989** 2024-03-07 07:40 UTC

**Comment by madilkha** [comment] 2024-03-07 08:40
Yes working now. thanks
