### ISSUE TITLE
Bug - Azure Functions Core Tools check doesn't recognise node v18 as a supported runtime.

### ISSUE THREAD

**Issue by Sealjay** [Azure/static-web-apps-cli#572] opened 2022-09-26 10:54 UTC
*Are you accessing the CLI from the default port `:4280` ?**

- [x] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
When running `swa start` on a mac with an install of Azure Functions Core Tools v4, and Node.js v18.9.1, the following error is produced:
```bash
Found Azure Functions Core Tools v4 which is incompatible with your current Node.js v18.9.1.
````

**More information**
In `static-web-apps-cli/src/core/func-core-tools.ts`, the check at line 45 is as follows:
```
return nodeVersion >= 14 && nodeVersion <= 16;
```
According to [the language support,](https://learn.microsoft.com/en-gb/azure/azure-functions/functions-versions?pivots=programming-language-javascript&tabs=azure-cli%2Cin-process%2Cv4#languages) the v18 (preview) is a supported node version, so the check should be changed.

e.g.
```
return nodeVersion >= 14 && nodeVersion <= 16 || nodeVersion === 18;
```

**To Reproduce**

1. Install node v18 of any version
2. Install Azure Functions Core Tools v4
3. Have a swa setup for node
4. Run `swa start`

**Expected behavior**
I expected `swa start` to run without error.

**Screenshots**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/19361656/192259215-94e48f2a-a717-4bfd-a904-448ff82d7a29.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version: v12.5.1

**Comment by Sealjay** [comment] 2022-09-26 10:55
https://github.com/Azure/static-web-apps-cli/blob/47823b006f25bfcbdeed6e27941b3e8ee5e7327a/src/core/func-core-tools.ts#L45

**Comment by sgollapudi77** [comment] 2022-09-26 12:00
Hey @Sealjay , this is a duplicate of the issue number - #568 . We'll be merging the PR fixing this soon.

**Closed by sgollapudi77** 2022-09-26 12:00 UTC

**Comment by Sealjay** [comment] 2022-09-26 12:07
Ahh sorry @sgollapudi77! I had a look for duplicates but the title didn't make it obvious 😅 I've downgraded to node v16 in the interim.
