### ISSUE TITLE
Proposal: swa-cli.config.json format evolution to support new commands

### ISSUE THREAD

**Issue by sinedied** [Azure/static-web-apps-cli#422] opened 2022-03-28 16:09 UTC
**Is your feature request related to a problem? Please describe.**
With the upcoming changes on the SWA CLI and the new commands being developed, it is currently a problem that we cannot set different values for options flags depending of the running command.

Concrete example of the problem:
- For `swa start`, I would like to use a dev server (`swa start http://localhost:4200`) which means the `context` value of my configuration would be `http://localhost:4200`.
- For `swa deploy`, I need to specify the output folder (`swa deploy ./dist`) which means the `context` value of my configuration would need to be `./dist`.

**Problem:** currently we can only set 1 `context` property, and we have to way to differentiate its value depending of command used.

**Describe the solution you'd like**
The proposed new format would be backward compatible with the current one, but would add an extra level to allow defining or overriding any option for a given command:

![Screenshot 2022-03-28 at 16 21 38](https://user-images.githubusercontent.com/593151/160434539-c0726657-af8c-40af-a7bc-305e4765f8ab.png)

With this proposition, options could still be defined "globally" (ie for all commands), and/or could be defined for a particular command. This would allow to handle use cases such as the example above, while not adding too much complexity and keeping compatibility with current format. Having the option of using both global and command-specific option also have the benefit of avoiding duplication for options that are identical between commands.

**Describe alternatives you've considered**
With @manekinekko, we've considered all these alternative approaches:
1. Adding a dedicated `overrides` property to allow overriding specific settings for each command => unneeded extra level, as we'll probably avoid having commands named the same as cli flags to avoid any confusion
1. Force an extra level for each command to have its own options => breaks compatibility, will need to duplication some options between commands
1. Add optional CLI flags that can be used as an alternative syntax in place of command context => this was the case with the start command and `--output-location` and cause confusion as it was possible to use both context and option, so it was removed
1. Add extra settings in the configuration that do no exists as CLI flags, but are injected in place of the context argument for each command (for example, outputLocation or startContext, deployContext) => having settings that do not match the CLI options would be confusing
1. Use existing `configurations` to create named profiles for each command, ie have a `app:start`, `app:deploy` etc configurations => would need reworking the configuration logic and make it prone to errors for grouping commands under the same "app" name
1. Allow to prefix configuration options with the name of the command to define or override it, for example `start:context` and `deploy:context` => would be hard to keep track of all settings related to given command

**Additional context**
With no pun intended, this may be also a good chance to rethink the usage of the `context` option in the configuration file.
The `context` option is currently exposed as an option in the configuration file (to use like `swa start <context>` for example), but it was initially meant to be an implementation detail to my understanding. So maybe, we could also reconsider option 3. in addition to the current proposal, to remove the need to expose the `context` setting in the configuration file.

This would allow to be more consistent with SWA options in the GitHub actions and the portal, as `context` have no meaning there but for example `output-location` has.
To avoid the initial confusion issue that resulted in its removal, we could simply detect if both context and its alternative options are set at the same time when calling the CLI and throw and error. 
For example, running `swa start http://localhost:4200 --output-location ./dist` would cause an error as both the context (`http://localhost:4200`) and `--output-location` flag are defined at the same time.

**Comment by alexweininger** [comment] 2022-03-28 16:36
> Use existing configurations to create named profiles for each command, ie have a app:start, app:deploy etc configurations => would need reworking the configuration logic and make it prone to errors for grouping commands under the same "app" name

The VS Code extension depends on a feature like this, since we need a way for users to provide their own command when the command we generate for them doesn't work. So I would ask for this approach to be included in the final implementation. I think it could be combined with a few of the other proposed approaches too.

> With no pun intended, this may be also a good chance to rethink the usage of the context option in the configuration file.

I think this would be a good idea, in our user studies the way `context` worked was confusing. And as you mention, there is not a clear relationship between `context` and the `swa-cli.config.json`.

**Comment by sinedied** [comment] 2022-03-29 08:05
> The VS Code extension depends on a feature like this, since we need a way for users to provide their own command when the command we generate for them doesn't work. So I would ask for this approach to be included in the final implementation. I think it could be combined with a few of the other proposed approaches too.

I'm not sure I fully understand what you meant here, would you require any changes to how `configurations` works currently? As in the initial proposal there's no plans to change its current behavior, so it will continue to work the same.
I probably miss some context as I thought the multiple configurations were meant for either monorepos (where you could have multiple apps in the same folder) or when you need different start configurations when using the VS Code extensions.

**Comment by manekinekko** [comment] 2022-04-10 00:43
Changes have landed in https://github.com/Azure/static-web-apps-cli/pull/432. Please open a new thread to discuss issues or regressions.

**Closed by manekinekko** 2022-04-10 00:43 UTC
Labels: type: enhancement, priority: high (P0), scope: cli, status: need unit tests, type: RFC, status: need internal approval, complexity: days
