### ISSUE TITLE
CLI fails to deploy application without reporting error details

### ISSUE THREAD

**Issue by tnabil** [Azure/static-web-apps-cli#608] opened 2022-11-22 05:31 UTC
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**

- [ ] No, I am using a different port number (`--port`) and accessing the CLI from that port
- [X] Yes, I am accessing the CLI from port `:4280`

> Make sure you are accessing the URL printed in the console when running `swa start`!

**ℹ️ NOTE: Make sure to enable debug logs when running any `swa` commands using `--verbose=silly`**

**Describe the bug**
Attempting to deploy using the CLI returns successfully without any errors, yet the deployment does not occur.

**To Reproduce**
1. Attempt to deploy an application from a Bamboo agent using the CLI
2. Deployment does not occur and CLI does not return any errors or explanation for the failure
3. The closest thing to an error message is `Could not get repository url. Proceeding`, which doesn't say much and also `Proceeding` implies that it is only a warning
4. The deployment is for a pre-generated build, so it should just be uploading

The exact command used is

npx @azure/static-web-apps-cli deploy &#92;
    ./public-dev &#92;
    --deployment-token $bamboo_swa_cli_deployment_secret &#92;
    -S 'REDACTED' &#92;
    -R 'ARG-StaticWebsiteHosting' &#92;
    -T 'REDACTED' &#92;
    --app-name 'nuxt3-static-web-app'

Note: I selected that I'm using port 4280 above because I haven't configured it otherwise, but I haven't seen this setting exposed anywhere.

**Expected behavior**
Deployment should occur

**Screenshots**
Full log of deployment:

build	22-Nov-2022 15:56:58	Welcome to Azure Static Web Apps CLI (1.0.3)
build	22-Nov-2022 15:56:58	
build	22-Nov-2022 15:56:58	Getting config file options from swa-cli.config.json...
build	22-Nov-2022 15:56:58	Config file does not exist at /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/swa-cli.config.json
build	22-Nov-2022 15:56:58	Deploying front-end files from folder:
build	22-Nov-2022 15:56:58	  /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	22-Nov-2022 15:56:58	
build	22-Nov-2022 15:56:58	Deployment token provided via flag
build	22-Nov-2022 15:56:58	 - --deployment-token: <hidden>
build	22-Nov-2022 15:56:58	
build	22-Nov-2022 15:56:58	Deploying to environment: preview
build	22-Nov-2022 15:56:58	
build	22-Nov-2022 15:56:58	Trying to read workflow config with values:
build	22-Nov-2022 15:56:58	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	22-Nov-2022 15:56:58	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	22-Nov-2022 15:56:58	 - apiLocation: <undefined>
build	22-Nov-2022 15:56:58	No workflow config folder found at /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/.github/workflows
build	22-Nov-2022 15:56:58	Validating user workflow config (BEFORE):
build	22-Nov-2022 15:56:58	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	22-Nov-2022 15:56:58	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	22-Nov-2022 15:56:58	 - apiLocation: <undefined>
build	22-Nov-2022 15:56:58	Validating user workflow config (AFTER):
build	22-Nov-2022 15:56:58	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	22-Nov-2022 15:56:58	 - apiLocation: <undefined>
build	22-Nov-2022 15:56:58	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	22-Nov-2022 15:56:58	No staticwebapp.config.json found in current project
build	22-Nov-2022 15:56:58	Deploying project to Azure Static Web Apps...
build	22-Nov-2022 15:56:58	Fetching release metadata for version: stable. Please wait...
build	22-Nov-2022 15:56:58	 - version: stable
build	22-Nov-2022 15:56:58	 - buildId: 1.0.020981
build	22-Nov-2022 15:56:58	 - publishDate: 2022-09-29T17:37:34.4094014Z
build	22-Nov-2022 15:56:58	- files:
build	22-Nov-2022 15:56:58	 - linux-x64:
build	22-Nov-2022 15:56:58	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient
build	22-Nov-2022 15:56:58	   - sha: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
build	22-Nov-2022 15:56:58	 - win-x64:
build	22-Nov-2022 15:56:58	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/windows/StaticSitesClient.exe
build	22-Nov-2022 15:56:58	   - sha: 4e4eb72aef26641e236c24929c822500e956bda099ca78054112cadf20261107
build	22-Nov-2022 15:56:58	 - osx-x64:
build	22-Nov-2022 15:56:58	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/macOS/StaticSitesClient
build	22-Nov-2022 15:56:58	   - sha: e0f2ae7ec297510a1b3b9332c0dc0dd962a51adb8ea13cd4f3746d79fc24a7e9
build	22-Nov-2022 15:56:58	Local client binary is up to date. Skipping download.
build	22-Nov-2022 15:56:58	Deploying using /home/bamboo/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
build	22-Nov-2022 15:56:58	Deploying using the following options:
build	22-Nov-2022 15:56:58	- env:
build	22-Nov-2022 15:56:58	  - SWA_CLI_DEBUG: silly
build	22-Nov-2022 15:56:58	  - SWA_RUNTIME_WORKFLOW_LOCATION: <undefined>
build	22-Nov-2022 15:56:58	  - SWA_RUNTIME_CONFIG_LOCATION: <undefined>
build	22-Nov-2022 15:56:58	  - SWA_RUNTIME_CONFIG: <undefined>
error	22-Nov-2022 15:56:58	- Preparing deployment. Please wait...
build	22-Nov-2022 15:56:58	  - SWA_CLI_VERSION: 1.0.3
build	22-Nov-2022 15:56:58	  - SWA_CLI_DEPLOY_DRY_RUN: false
build	22-Nov-2022 15:56:58	  - SWA_CLI_DEPLOY_BINARY: /home/bamboo/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
build	22-Nov-2022 15:56:58	  - DEPLOYMENT_ACTION: upload
build	22-Nov-2022 15:56:58	  - DEPLOYMENT_PROVIDER: SwaCli
build	22-Nov-2022 15:56:58	  - REPOSITORY_BASE: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	22-Nov-2022 15:56:58	  - SKIP_APP_BUILD: true
build	22-Nov-2022 15:56:58	  - SKIP_API_BUILD: true
build	22-Nov-2022 15:56:58	  - DEPLOYMENT_TOKEN: <hidden>
build	22-Nov-2022 15:56:58	  - APP_LOCATION: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	22-Nov-2022 15:56:58	  - API_LOCATION: <undefined>
build	22-Nov-2022 15:56:58	  - CONFIG_FILE_LOCATION: <undefined>
build	22-Nov-2022 15:56:58	  - VERBOSE: true
build	22-Nov-2022 15:56:58	  - DEPLOYMENT_ENVIRONMENT: preview
error	22-Nov-2022 15:56:58	? [37mDeploymentId: 1107571c-c854-47a2-a878-478e133f3da7[0m
error	22-Nov-2022 15:56:58	? [37m[0m
error	22-Nov-2022 15:56:58	? [37mVerbose logging enabled[0m
error	22-Nov-2022 15:56:58	? [37mBuild timeout not specified, defaulting to 15 minutes[0m
error	22-Nov-2022 15:56:58	? [37mApp Directory Location: '/media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev' was found.[0m
error	22-Nov-2022 15:56:58	? [37mLooking for event info[0m
error	22-Nov-2022 15:56:58	? [37mEvent info parsed from action options.[0m
error	22-Nov-2022 15:56:58	? [37mCould not get repository branch. Proceeding[0m
error	22-Nov-2022 15:56:58	? [37mCould not get repository url. Proceeding[0m
error	22-Nov-2022 16:05:39	? [37m[0m
error	22-Nov-2022 16:05:39	? [33mFor further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/[0m
error	22-Nov-2022 16:05:39	? [33mIf you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/[0m
simple	22-Nov-2022 16:05:39	Finished task 'Deploy - script' with result: Success
simple	22-Nov-2022 16:05:39	Finalising the build...
simple	22-Nov-2022 16:05:39	Stopping timer.
simple	22-Nov-2022 16:05:39	Build 33652749-33423430-32378285 completed.
simple	22-Nov-2022 16:05:39	Finished processing deployment result Deployment of '1.4.0' on 'dev'

**Desktop (please complete the following information):**

- OS: Amazon Linux 2
- Version: Latest

**Additional context**

**Comment by sulabh-msft** [comment] 2022-11-24 06:43
Dupe of https://github.com/Azure/static-web-apps-cli/issues/595

**Comment by tnabil** [comment] 2022-11-24 06:48
Hi @sulabh-msft,
I went through the linked issue and I'm not sure if the root cause is the same. My application does not have an API, it's only a bunch of static assets.
Assuming it is the same, would providing a minimal config file solve this?

**Comment by tnabil** [comment] 2022-11-24 06:54
Actually, just referred back to the docs at https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy, the config file is not required where there is no API.
Also, the debug messages that were displayed prior to the failure in the linked ticket were not printed out in my case. I think we are looking at a completely different issue here.

**Comment by tnabil** [comment] 2022-11-24 07:10
I noticed that it takes a significant amount of time for the deployment to fail. This makes me think that the URL that the client is trying to deploy to could be blocked by our firewall. Given that the client is closed-source, I don't know the exact endpoint it is trying to call.
We currently have the following URLs white-listed. Is the endpoint the client is talking to covered by this list?
- *.microsoft.com
- *.microsoftonline.com
- *.microsoftonline-p.com
- *.windows.net
- *.azure.com
- *.azure.net
- *.azure-api.net

**Comment by tnabil** [comment] 2022-11-25 05:17
Any updates on the Azure endpoints that we need to whitelist in order for the deployment to work?

**Comment by sgollapudi77** [comment] 2022-12-01 06:01
Hey @tnabil, can you try running the command with this flag `--verbose=silly` which gives us more context about the issue.

**Comment by tnabil** [comment] 2022-12-01 06:45
Hi @sgollapudi77, the logs above were produced with the `silly` logging level. You can't see it in the command because I had set it using the `SWA_CLI_DEBUG` environment variable as follows:
`
export SWA_CLI_DEBUG=silly
`
Really, all I need is to know is the hostnames of the endpoints the tool is calling so that I can get them white-listed. I have a strong feeling this is going to fix the issue. I know the tool is closed source but I believe knowing the endpoints it calls is a legitamite request for anyone running an on-premises CI/CD platform.

**Comment by tnabil** [comment] 2022-12-01 07:20
Just in case, I ran it again with the flag, and here's the output.

build	01-Dec-2022 18:04:26	Welcome to Azure Static Web Apps CLI (1.0.3)
build	01-Dec-2022 18:04:26	
build	01-Dec-2022 18:04:26	Getting config file options from swa-cli.config.json...
build	01-Dec-2022 18:04:26	Config file does not exist at /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/swa-cli.config.json
build	01-Dec-2022 18:04:26	Deploying front-end files from folder:
build	01-Dec-2022 18:04:26	  /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	01-Dec-2022 18:04:26	
build	01-Dec-2022 18:04:26	Deployment token provided via flag
build	01-Dec-2022 18:04:26	 - --deployment-token: <hidden>
build	01-Dec-2022 18:04:26	
build	01-Dec-2022 18:04:26	Deploying to environment: preview
build	01-Dec-2022 18:04:26	
build	01-Dec-2022 18:04:26	Trying to read workflow config with values:
build	01-Dec-2022 18:04:26	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	01-Dec-2022 18:04:26	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	01-Dec-2022 18:04:26	 - apiLocation: <undefined>
build	01-Dec-2022 18:04:26	No workflow config folder found at /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/.github/workflows
build	01-Dec-2022 18:04:26	Validating user workflow config (BEFORE):
build	01-Dec-2022 18:04:26	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	01-Dec-2022 18:04:26	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	01-Dec-2022 18:04:26	 - apiLocation: <undefined>
build	01-Dec-2022 18:04:26	Validating user workflow config (AFTER):
build	01-Dec-2022 18:04:26	 - appLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	01-Dec-2022 18:04:26	 - apiLocation: <undefined>
build	01-Dec-2022 18:04:26	 - outputLocation: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	01-Dec-2022 18:04:26	No staticwebapp.config.json found in current project
build	01-Dec-2022 18:04:26	Deploying project to Azure Static Web Apps...
build	01-Dec-2022 18:04:26	Could not find StaticSitesClient local binary
build	01-Dec-2022 18:04:26	Fetching release metadata for version: stable. Please wait...
build	01-Dec-2022 18:04:27	 - version: stable
build	01-Dec-2022 18:04:27	 - buildId: 1.0.020981
build	01-Dec-2022 18:04:27	 - publishDate: 2022-09-29T17:37:34.4094014Z
build	01-Dec-2022 18:04:27	- files:
build	01-Dec-2022 18:04:27	 - linux-x64:
build	01-Dec-2022 18:04:27	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient
build	01-Dec-2022 18:04:27	   - sha: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
error	01-Dec-2022 18:04:27	- Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient@1.0.020981
build	01-Dec-2022 18:04:27	 - win-x64:
build	01-Dec-2022 18:04:27	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/windows/StaticSitesClient.exe
build	01-Dec-2022 18:04:27	   - sha: 4e4eb72aef26641e236c24929c822500e956bda099ca78054112cadf20261107
build	01-Dec-2022 18:04:27	 - osx-x64:
build	01-Dec-2022 18:04:27	   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/macOS/StaticSitesClient
build	01-Dec-2022 18:04:27	   - sha: e0f2ae7ec297510a1b3b9332c0dc0dd962a51adb8ea13cd4f3746d79fc24a7e9
error	01-Dec-2022 18:04:30	[swa] ? Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient@1.0.020981
build	01-Dec-2022 18:04:30	Checksum match: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
build	01-Dec-2022 18:04:30	Saved binary to /home/bamboo/.swa/deploy/1.0.020981/StaticSitesClient
build	01-Dec-2022 18:04:30	Saved metadata to /home/bamboo/.swa/deploy/StaticSitesClient.json
build	01-Dec-2022 18:04:30	Deploying using /home/bamboo/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
build	01-Dec-2022 18:04:30	Deploying using the following options:
build	01-Dec-2022 18:04:30	- env:
build	01-Dec-2022 18:04:30	  - SWA_CLI_DEBUG: silly
build	01-Dec-2022 18:04:30	  - SWA_RUNTIME_WORKFLOW_LOCATION: <undefined>
build	01-Dec-2022 18:04:30	  - SWA_RUNTIME_CONFIG_LOCATION: <undefined>
build	01-Dec-2022 18:04:30	  - SWA_RUNTIME_CONFIG: <undefined>
build	01-Dec-2022 18:04:30	  - SWA_CLI_VERSION: 1.0.3
build	01-Dec-2022 18:04:30	  - SWA_CLI_DEPLOY_DRY_RUN: false
build	01-Dec-2022 18:04:30	  - SWA_CLI_DEPLOY_BINARY: /home/bamboo/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
build	01-Dec-2022 18:04:30	  - DEPLOYMENT_ACTION: upload
build	01-Dec-2022 18:04:30	  - DEPLOYMENT_PROVIDER: SwaCli
build	01-Dec-2022 18:04:30	  - REPOSITORY_BASE: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430
build	01-Dec-2022 18:04:30	  - SKIP_APP_BUILD: true
build	01-Dec-2022 18:04:30	  - SKIP_API_BUILD: true
build	01-Dec-2022 18:04:30	  - DEPLOYMENT_TOKEN: <hidden>
error	01-Dec-2022 18:04:30	- Preparing deployment. Please wait...
build	01-Dec-2022 18:04:30	  - APP_LOCATION: /media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev
build	01-Dec-2022 18:04:30	  - API_LOCATION: <undefined>
build	01-Dec-2022 18:04:30	  - CONFIG_FILE_LOCATION: <undefined>
build	01-Dec-2022 18:04:30	  - VERBOSE: true
build	01-Dec-2022 18:04:30	  - DEPLOYMENT_ENVIRONMENT: preview
error	01-Dec-2022 18:04:32	? [37mDeploymentId: 06e0f1f3-1a6c-44c4-9612-8c81cffa98aa[0m
error	01-Dec-2022 18:04:32	? [37m[0m
error	01-Dec-2022 18:04:32	? [37mVerbose logging enabled[0m
error	01-Dec-2022 18:04:33	? [37mBuild timeout not specified, defaulting to 15 minutes[0m
error	01-Dec-2022 18:04:33	? [37mApp Directory Location: '/media/atl/bamboo-agent-home/xml-data/build-dir/33652749-33423430/public-dev' was found.[0m
error	01-Dec-2022 18:04:33	? [37mLooking for event info[0m
error	01-Dec-2022 18:04:33	? [37mEvent info parsed from action options.[0m
error	01-Dec-2022 18:04:33	? [37mCould not get repository branch. Proceeding[0m
error	01-Dec-2022 18:04:33	? [37mCould not get repository url. Proceeding[0m
error	01-Dec-2022 18:13:13	? [37m[0m
error	01-Dec-2022 18:13:13	? [33mFor further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/[0m
error	01-Dec-2022 18:13:13	? [33mIf you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/[0m

You will notice that there are 9 minutes between these two log entries:

error	01-Dec-2022 18:04:33	? [37mCould not get repository url. Proceeding[0m
error	01-Dec-2022 18:13:13	? [37m[0m

This can only be caused by a firewall blocking the requests.

**Comment by tnabil** [comment] 2022-12-06 04:08
For those who land on this issue looking for a resolution, I've done some network analysis using wireshark and determined that the following domains and all their subdomains need to be white-listed in order for the CLI to work. This has been successfully tested on our on-premises build servers after the white-listing was done:
- blob.core.windows.net
- azurestaticapps.net
- swalocaldeploy.azureedge.net

**Comment by sgollapudi77** [comment] 2022-12-06 10:06
Thanks @tnabil , we'll add these info to the docs.

**Closed by sgollapudi77** 2022-12-06 10:06 UTC
Labels: status: duplicate
