### ISSUE TITLE
Query parameters to static pages parsed incorrectly.

### ISSUE THREAD

**Issue by dwmuller** [Azure/static-web-apps-cli#350] opened 2021-11-20 21:00 UTC
Before filing this issue, please ensure you're using the latest CLI by running `swa --version` and comparing to the latest version on [npm](https://www.npmjs.com/package/@azure/static-web-apps-cli).

**Are you accessing the CLI from the default port `:4280` ?**
- [ ] No, I am using a different port number (--port) and accessing the CLI from that port
- [x] Yes, I am accessing the CLI from port `:4280`

**Describe the bug**
Using swa CLI 0.8.1, in local testing, query parameters in a static page request seem to get parsed incorrectly. A request for a page like http://localhost:4280/search/?query=foo is interpreted as a request for page /search/query=foo. Similarly, a request for /search?query=foo is interpreted as a request for page /searchquery=foo. (The page in question has javascript which accesses the query parameters.)

Rolling back to CLI version 0.8.0 restored correct behavior.

**To Reproduce**
1. Run any SWA app with static pages locally.
2. Visit a page in the browser.
3. Append any query parameters to the URL and try again.
4. Note the 404 error with text referencing an incorrect path.

**Expected behavior**
Adding query parameters should not affect the requested page path.

**Screenshots**
![image](https://user-images.githubusercontent.com/17508429/142740752-243372ab-8c08-4c0b-8f1c-7c6f255936d4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 (WSL)
 - Browser: Firefox on Windows host

**Comment by manekinekko** [comment] 2021-11-22 16:28
Thank you for opening this issue. This should be fixed by PR #338.

**Comment by manekinekko** [comment] 2021-11-22 16:29
FYI, this is also a duplicate of #346

**Closed** 2021-11-24 06:42 UTC
Labels: type: bug, status: duplicate
