### ISSUE TITLE
swa deletes .git folder 

### ISSUE THREAD

**Issue by johnkors** [Azure/static-web-apps-cli#550] opened 2022-09-02 10:21 UTC
**Describe the bug**
swa deploy deletes the `.git` folder.

**To Reproduce**
1. Create a git repo
2. Setup a `swa-cli.config.json` with `outputLocation: "./"`
3. Run deploy

**Expected behavior**
Keeping my `.git` folder.

SWA version 1.0.2

**Comment by andreyrd** [comment] 2023-05-05 18:06
I would say this is much higher than "medium" priority.

**Comment by cjk7989** [comment] 2023-09-04 11:59
Hi guys, thank you for reporting this bug, I’m investigating it. If you encounter this issue, could you tell me which framework did you use? (such as angular, react, etc.) It will be good to show the files and folders in the root path of your app.

In addition, I guess your appLocation was the same as the root path, or you didn't set the appLocation. Am I right?

**Comment by cjk7989** [comment] 2023-11-07 06:55
The bug has been fixed in swa-cli@v1.1.5. Thanks for the feedback and will close this issue.

**Closed by cjk7989** 2023-11-07 06:55 UTC
Labels: priority: medium (P1), command: deploy, scope: deploy-client

**Comment by DavidDeVries** [comment] 2024-01-20 14:24
This same bug is happening now for me in v1.1.6

**Comment by FelixZY** [comment] 2024-03-28 19:52
+1 just had this happen in v1.1.7. All my git progress was local so far :sob:

**Comment by PhilippVogel92** [comment] 2024-04-12 08:42
+1 happen in v1.1.7.

**Comment by tib-c** [comment] 2024-07-18 05:52
+1 happened in v1.1.10

Config:
`"outputLocation": "dist\\<buildAppDir>",`

**Comment by FelixZY** [comment] 2024-07-18 07:28
@cjk7989 it seems the issue is not resolved. Could this please be reopened?

**Comment by crebma** [comment] 2025-02-12 22:55
This is happening to me today, version 2.0.3. Please reopen.

**Comment by FelixZY** [comment] 2025-02-13 13:52
Looks like nobody on the Microsoft side is receiving any notifications. Attempting to remedy this by pinging previously assigned people: @sgollapudi77 @sulabh-msft @Reshmi-Sriram @rupareddy5-21

**Comment by vsoldatkin** [comment] 2025-03-04 15:09
Accidentally found this issue here. Now I suspect this to be the cause of my .git folder mysteriously disappearing without trace once. I didn't notice the precise moment it happened, so I almost started to doubt my sanity, haha.. No, not a funny issue at all.

**Comment by je-sidestuff** [comment] 2025-05-04 20:47
This is still broken guys.

Can we get some indication you are seeing these messages?
