### ISSUE TITLE
Installed version is 1.0.1 but package.json shows 1.0.2, unable to install 1.0.2

### ISSUE THREAD

**Issue by gregholst** [Azure/static-web-apps-cli#532] opened 2022-07-01 18:19 UTC
**Describe the bug**
Although installation of SWA shows version 1.0.2 in package.json, only version 1.0.1 is installed

**To Reproduce**

1. Uninstall previous version: npm uninstall @azure/static-web-apps-cli 
2. New install: npm install -D @azure/static-web-apps-cli
3. Read package.json: "@azure/static-web-apps-cli": "^1.0.2" (added as dev dependency)
4. Run version check: swa --version (shows 1.0.1)
4b. Run my software: swa start build --api-location api 
// shows among other information:
// Welcome to Azure Static Web Apps CLI (1.0.1)
// Only sometimes shows: Update available 1.0.1 → 1.0.2            │
   │   Run npm i @azure/static-web-apps-cli to update 
5. Run again: npm install -D @azure/static-web-apps-cli
// up to date, audited 1676 packages in 7s
6. Run specific install: npm install -D @azure/static-web-apps-cli@1.0.2
// no difference to above described behaviour

**Expected behavior**
swa -v will show version 1.0.2

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS:  MacOS
- Version 12.4 (Monterey)

**Additional context**
Other used software, probably not relevant...
[api] Found Python version 3.9.12 (python3).
[api] Azure Functions Core Tools
[api] Core Tools Version:       4.0.4483 Commit hash: N/A  (64-bit)
[api] Function Runtime Version: 4.1.3.17473

**Comment by sgollapudi77** [comment] 2022-07-29 05:24
Hey @gregholst, not able to reproduce on our end, please try installing the latest version and verify if you're still facing this issue.

**Comment by Reshmi-Sriram** [comment] 2022-08-12 08:45
Closing the issue. Feel free to re-open if necessary!

**Closed by Reshmi-Sriram** 2022-08-12 08:45 UTC
